//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.30 at 08:33:13 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://promotion.engine.org/schema")
package org.engine.promotion.schema;
