//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.07.01 at 05:43:27 PM BST 
//


package org.engine.promotion.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="skuItem" type="{http://promotion.engine.org/schema}SKUItem" maxOccurs="unbounded"/>
 *         &lt;element name="promotionItem" type="{http://promotion.engine.org/schema}PromotionItem" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "skuItem",
    "promotionItem"
})
@XmlRootElement(name = "PromotionRules")
public class PromotionRules {

    @XmlElement(required = true)
    protected List<SKUItem> skuItem;
    @XmlElement(required = true)
    protected List<PromotionItem> promotionItem;

    /**
     * Gets the value of the skuItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skuItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkuItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SKUItem }
     * 
     * 
     */
    public List<SKUItem> getSkuItem() {
        if (skuItem == null) {
            skuItem = new ArrayList<SKUItem>();
        }
        return this.skuItem;
    }

    /**
     * Gets the value of the promotionItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PromotionItem }
     * 
     * 
     */
    public List<PromotionItem> getPromotionItem() {
        if (promotionItem == null) {
            promotionItem = new ArrayList<PromotionItem>();
        }
        return this.promotionItem;
    }

}
